name: AutoUI Discussion Bot (Vue + AntV)

on:
  discussion:
    types: [created, labeled, edited]
  discussion_comment:
    types: [created, edited]

permissions:
  contents: write
  discussions: write

jobs:
  autoui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- sanity ----------
      - name: Verify templates exist
        shell: bash
        run: |
          set -euo pipefail
          test -f .github/templates/autoui/questions.json
          test -f .github/templates/autoui/reply.md
          test -f .github/templates/autoui/Landing.vue.template
          test -f .github/templates/autoui/StatsChart.vue.template
          echo "All templates present."

      # ---------- parse discussion ----------
      - name: Parse discussion + decide next question
        id: decide
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");

            const cfg = JSON.parse(
              fs.readFileSync(".github/templates/autoui/questions.json", "utf8")
            );

            const discussionId = context.payload.discussion.node_id;

            const q = `
            query($id: ID!) {
              node(id: $id) {
                ... on Discussion {
                  body
                  labels(first: 20) { nodes { name } }
                  comments(first: 100) {
                    nodes {
                      body
                      author { login }
                    }
                  }
                }
              }
            }`;

            const data = await github.graphql(q, { id: discussionId });
            const node = data.node;

            const labels = node.labels.nodes.map(l => l.name);
            if (!labels.includes("AutoUI")) {
              core.setOutput("complete", "false");
              core.setOutput("next_question", "");
              core.setOutput("status_block", "AutoUI label missing.");
              return;
            }

            const allQuestions = cfg.sections.flatMap(s =>
              s.questions.map(q => ({ ...q, section: s }))
            );

            const textBlob = [
              node.body || "",
              ...node.comments.nodes.map(c => c.body || "")
            ].join("\n\n");

            const answers = {};
            for (const q of allQuestions) {
              const re = new RegExp(
                `(?:^|\\n)\\s*${q.key}\\s*(?:=|:)\\s*([^\\n]+)`,
                "i"
              );
              const m = textBlob.match(re);
              if (m) answers[q.key] = m[1].trim();
            }

            const botLogin = "github-actions[bot]";
            const lastHuman = [...node.comments.nodes]
              .reverse()
              .find(c => c.author?.login !== botLogin);

            const wantsSkip = lastHuman
              ? /(^|\s)(skip|next)(\s|$)/i.test(lastHuman.body)
              : false;

            const nextQ = allQuestions.find(q => !answers[q.key]);

            fs.writeFileSync("/tmp/autoui-answers.json", JSON.stringify(answers, null, 2));

            core.setOutput("complete", nextQ ? "false" : "true");
            core.setOutput("pending_key", nextQ?.key || "");
            core.setOutput("section_id", nextQ?.section.id || "");
            core.setOutput("section_title", nextQ?.section.title || "");
            core.setOutput("section_intro", nextQ?.section.intro || "");
            core.setOutput(
              "section_links",
              (nextQ?.section.links || []).map(l => `- ${l}`).join("\n")
            );
            core.setOutput(
              "next_question",
              nextQ
                ? `${nextQ.ask}\n\n${
                    nextQ.options?.length
                      ? "**Options:**\n" + nextQ.options.map(o => `- ${o}`).join("\n")
                      : ""
                  }\n\nReply with:\n- \`${nextQ.key}=...\`\n- or \`skip\` / \`next\``
                : ""
            );
            core.setOutput("wants_skip", wantsSkip ? "true" : "false");

            const status = cfg.sections.map(s => {
              const lines = s.questions.map(q => {
                const v = answers[q.key];
                if (!v) return `- \`${q.key}\`: ❌`;
                if (v === "__SKIP__") return `- \`${q.key}\`: ⏭️ skipped`;
                return `- \`${q.key}\`: ✅ ${v}`;
              });
              return `### ${s.title}\n${lines.join("\n")}`;
            }).join("\n\n");

            core.setOutput("status_block", status);

      # ---------- persist skip ----------
      - name: Persist skip marker
        if: ${{ steps.decide.outputs.wants_skip == 'true' && steps.decide.outputs.pending_key != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const key = "${{ steps.decide.outputs.pending_key }}";
            const body = `${key}=__SKIP__\n\n<!-- autoui:skip=${key} -->`;

            await github.graphql(
              `mutation($id: ID!, $body: String!) {
                addDiscussionComment(input: { discussionId: $id, body: $body }) {
                  comment { id }
                }
              }`,
              { id: context.payload.discussion.node_id, body }
            );

      # ---------- reply ----------
      - name: Render reply
        if: ${{ steps.decide.outputs.complete == 'false' }}
        shell: bash
        run: |
          export STATUS_BLOCK="${{ steps.decide.outputs.status_block }}"
          export NEXT_QUESTION="${{ steps.decide.outputs.next_question }}"
          export SECTION_TITLE="${{ steps.decide.outputs.section_title }}"
          export SECTION_INTRO="${{ steps.decide.outputs.section_intro }}"
          export SECTION_LINKS="${{ steps.decide.outputs.section_links }}"
          export QUESTION_KEY="${{ steps.decide.outputs.pending_key }}"
          envsubst < .github/templates/autoui/reply.md > /tmp/reply.md

      - name: Comment question
        if: ${{ steps.decide.outputs.complete == 'false' }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const body = fs.readFileSync("/tmp/reply.md", "utf8");
            await github.graphql(
              `mutation($id: ID!, $body: String!) {
                addDiscussionComment(input: { discussionId: $id, body: $body }) {
                  comment { id }
                }
              }`,
              { id: context.payload.discussion.node_id, body }
            );

      # ---------- build & deploy ----------
      - name: Setup Node
        if: ${{ steps.decide.outputs.complete == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Vue
        if: ${{ steps.decide.outputs.complete == 'true' }}
        shell: bash
        run: |
          cd coming-soon
          npm ci || npm install
          npm run build

      - name: Deploy /beta (AI only)
        if: ${{ steps.decide.outputs.complete == 'true' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: coming-soon/dist
          destination_dir: beta
          keep_files: true

      - name: Comment completion
        if: ${{ steps.decide.outputs.complete == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const isUserSite = repo === `${owner}.github.io`;
            const url = isUserSite
              ? `https://${owner}.github.io/beta/`
              : `https://${owner}.github.io/${repo}/beta/`;

            const body = `✅ **AutoUI complete**\n\n🚀 Beta deployed:\n${url}`;
            await github.graphql(
              `mutation($id: ID!, $body: String!) {
                addDiscussionComment(input: { discussionId: $id, body: $body }) {
                  comment { id }
                }
              }`,
              { id: context.payload.discussion.node_id, body }
            );
